[project]
name = "lore-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langextract>=1.1.1",
    "openai>=2.18.0",
    "pymupdf>=1.26.7",
    "python-dotenv>=1.2.1",
]
